dist: xenial
language: node_js
node_js:
  - "10"
script: 
  - node tcp_proxy_test.js
  - node hexify_benchmark.js
notifications:
  email:
    recipients:
      - ademin@gmail.com
    on_success: always
    on_failure: always
