dist: xenial
language: node_js
node_js:
  - "10"
script: 
  - node hexify_test.js
  - node argv_test.js
  - node flags_test.js
  - node hexify_benchmark.js
  - npm install --save-dev jest
  - npm run test
notifications:
  email:
    recipients:
      - ademin@gmail.com
    on_success: always
    on_failure: always
